app = "order-bot-3820gq"

[env]
  PORT = "8080"
  WEBHOOK_DOMAIN = "https://your-app-name.fly.dev"
  BOT_TOKEN = "7788562064:AAHlN4EvhMnpLSPXcZ39lcYM9f7Hm6c3Fas"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
