app = "order-bot-kbkvpq"

[env]
  PORT = "8080"
  DEV_MODE = "false"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[mounts]
  source = "order_data"
  destination = "/data"
  # Add these new parameters:
  initial_size = "1"  # in GB
  auto_extend_size = "2"  # max size in GB
  auto_extend_threshold = "90"  # percentage used
